### PR TITLE
Add no_std support.

### PR DESCRIPTION
**Pull request by gbip**
Hi !
I needed `no_std` support for an other crates that depends on `try_from` so I implemented it.

Feel free to tell me if there is anything that I need to change !

### CODE REVIEW

**Comment by derekjw** [comment]
Sorry, I missed this! I'll get this done ASAP, thanks

**Comment by derekjw** [comment]
0.3.0 has been released to cargo.io

**Comment by derekjw** [comment]
@gbip I haven't used no_std before, so I'm a bit unfamiliar with it. It seems that tests aren't running now after I merged this change, and I can't see why. Do you have any ideas?

**Comment by gbip** [comment]
I just cloned the repository and `cargo test` seemed to run fine (but there is no tests).
Are you talking about CI integration ?

I might have forgotten to add the `default` feature in `Cargo.toml` but after reading [The Manifest Format](https://doc.rust-lang.org/cargo/reference/manifest.html) it does not [look](https://doc.rust-lang.org/cargo/reference/manifest.html#the-features-section) like mandatory.

**Comment by derekjw** [comment]
The tests are mixed into the library code. If you check out commit b1f674ed71 and run `cargo test` you'll get test output.

**Comment by gbip** [comment]
It is a very strange issue because it seems that the test are compiled, but they are not executed...

**Comment by derekjw** [comment]
Yeah, I'm quite stumped. I might try moving tests into the test folder later to see if that makes a difference.

**Comment by gbip** [comment]
I found the culprit : if you remove 
```rust
#![cfg(feature = "no_std")]
#![no_std]
```
from the top of `lib.rs` tests are running.

I think there is an extra `!` in `#![cfg(feature = "no_std")]` ...

I will make a PR fixing this as soon as possible.

**Pull request merged**
